### ISSUE TITLE
pdfmm won't reduce pdf

### ISSUE THREAD

**Issue by MrTen01** [jpfleury/pdfmm#3]
Since ghostscript 9.23, pdfmm won't reduce the pdf.

I find this 
[https://stackoverflow.com/questions/51267475/ghostscript-shrinking-pdf-doesnt-work-anymore](url)

simply replace the line 327 of pdfmm by this one

`gs -dBATCH -dNOPAUSE -q -dPassThroughJPEGImages=false -sDEVICE=pdfwrite -dPDFSETTINGS=/default \`

now the reduce is good.

**Comment by jpfleury** [comment]
Thanks a lot. Fixed in the master branch.
